[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F746NGHx --speed 500"
linker = "flip-link"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "debug"
